apiVersion: v1
kind: Service
metadata:
  name: world-service
  labels:
    app.kubernetes.io/name: hello
    component: world
spec:
  selector:
    component: world
  ports:
  - protocol: TCP
    port: 9999 # The advertised port of the service
    targetPort: 3000 # The port in the pods to forward to
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: world-deployment
  labels:
    component: world
    app.kubernetes.io/name: hello
spec:
  replicas: 2
  selector:
    matchLabels:
      component: world
  template:
    metadata:
      labels:
        component: world
    spec:
      containers:
      - name: world
        image: world-multilang:1.0
        ports:
        - containerPort: 3000 # specify which container port to open
        env:
        - name: LANG
          valueFrom:
            configMapKeyRef:
              name: hello-world-config
              key: lang